const carsData = [
  {
    id: "001",
    brand: "Toyota",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.5",
    rentPrice: "350",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "002",
    brand: "Honda",
    capacity: "4",
    fuelType: "Petrol",
    mileage: "7.2",
    rentPrice: "320",
    year: 2021,
    mode: "Manual",
    like: false,
  },
  {
    id: "003",
    brand: "Ford",
    capacity: "5",
    fuelType: "Diesel",
    mileage: "8.0",
    rentPrice: "400",
    year: 2019,
    mode: "Automatic",
    like: false,
  },
  {
    id: "004",
    brand: "Chevrolet",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "6.8",
    rentPrice: "330",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "005",
    brand: "Volkswagen",
    capacity: "5",
    fuelType: "Hybrid",
    mileage: "7.5",
    rentPrice: "360",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "006",
    brand: "Nissan",
    capacity: "4",
    fuelType: "Electric",
    mileage: "4.0",
    rentPrice: "300",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "007",
    brand: "Kia",
    capacity: "5",
    fuelType: "Diesel",
    mileage: "7.8",
    rentPrice: "370",
    year: 2019,
    mode: "Manual",
    like: false,
  },
  {
    id: "008",
    brand: "Hyundai",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "7.0",
    rentPrice: "340",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "009",
    brand: "Mazda",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.5",
    rentPrice: "350",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "010",
    brand: "Subaru",
    capacity: "5",
    fuelType: "Electric",
    mileage: "4.2",
    rentPrice: "310",
    year: 2021,
    mode: "Manual",
    like: false,
  },
  {
    id: "011",
    brand: "Audi",
    capacity: "4",
    fuelType: "Diesel",
    mileage: "7.5",
    rentPrice: "380",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "012",
    brand: "BMW",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "8.2",
    rentPrice: "420",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "013",
    brand: "Mercedes-Benz",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.7",
    rentPrice: "360",
    year: 2019,
    mode: "Automatic",
    like: false,
  },
  {
    id: "014",
    brand: "Volvo",
    capacity: "5",
    fuelType: "Diesel",
    mileage: "7.0",
    rentPrice: "370",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "015",
    brand: "Lexus",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.3",
    rentPrice: "350",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "016",
    brand: "Tesla",
    capacity: "4",
    fuelType: "Electric",
    mileage: "4.5",
    rentPrice: "310",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "017",
    brand: "Jaguar",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "8.5",
    rentPrice: "430",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "018",
    brand: "Land Rover",
    capacity: "5",
    fuelType: "Diesel",
    mileage: "7.2",
    rentPrice: "390",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "019",
    brand: "Porsche",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "9.0",
    rentPrice: "450",
    year: 2019,
    mode: "Automatic",
    like: false,
  },
  {
    id: "020",
    brand: "Ferrari",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "7.8",
    rentPrice: "420",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "021",
    brand: "Maserati",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "8.3",
    rentPrice: "430",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "022",
    brand: "Rolls-Royce",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.0",
    rentPrice: "480",
    year: 2019,
    mode: "Automatic",
    like: false,
  },
  {
    id: "023",
    brand: "Bentley",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "7.1",
    rentPrice: "460",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "024",
    brand: "Aston Martin",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "8.6",
    rentPrice: "440",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "025",
    brand: "McLaren",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "7.4",
    rentPrice: "470",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "026",
    brand: "Bugatti",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "6.5",
    rentPrice: "490",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "027",
    brand: "Lamborghini",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "7.8",
    rentPrice: "470",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "028",
    brand: "Lotus",
    capacity: "2",
    fuelType: "Gasoline",
    mileage: "8.2",
    rentPrice: "450",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "029",
    brand: "Alfa Romeo",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "7.0",
    rentPrice: "410",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "030",
    brand: "Acura",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "7.5",
    rentPrice: "390",
    year: 2020,
    mode: "Automatic",
    like: false,
  },

  {
    id: "031",
    brand: "Toyota",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.8",
    rentPrice: "350",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "032",
    brand: "Nissan",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.2",
    rentPrice: "370",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "033",
    brand: "Honda",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.5",
    rentPrice: "360",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "034",
    brand: "Kia",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.1",
    rentPrice: "380",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "035",
    brand: "Ford",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.7",
    rentPrice: "360",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "036",
    brand: "Chevrolet",
    capacity: "4",
    fuelType: "Electric",
    mileage: "4.8",
    rentPrice: "310",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "037",
    brand: "Hyundai",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.3",
    rentPrice: "390",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "038",
    brand: "Mazda",
    capacity: "5",
    fuelType: "Hybrid",
    mileage: "5.6",
    rentPrice: "360",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "039",
    brand: "Subaru",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.0",
    rentPrice: "400",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "040",
    brand: "Volkswagen",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.9",
    rentPrice: "370",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "041",
    brand: "Chrysler",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.4",
    rentPrice: "410",
    year: 2022,
    mode: "Manual",
    like: false,
  },
  {
    id: "042",
    brand: "Dodge",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.2",
    rentPrice: "400",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "043",
    brand: "Jeep",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.8",
    rentPrice: "420",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "044",
    brand: "Ram",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "6.1",
    rentPrice: "390",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "045",
    brand: "Volvo",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.6",
    rentPrice: "430",
    year: 2020,
    mode: "Manual",
    like: false,
  },
  {
    id: "046",
    brand: "Audi",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.4",
    rentPrice: "380",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "047",
    brand: "Lexus",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.5",
    rentPrice: "420",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "048",
    brand: "Infiniti",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.8",
    rentPrice: "390",
    year: 2020,
    mode: "Manual",
    like: false,
  },
  {
    id: "049",
    brand: "Porsche",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "7.0",
    rentPrice: "450",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "050",
    brand: "Tesla",
    capacity: "5",
    fuelType: "Electric",
    mileage: "4.5",
    rentPrice: "500",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "051",
    brand: "Nissan",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.7",
    rentPrice: "370",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "052",
    brand: "Honda",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.0",
    rentPrice: "380",
    year: 2021,
    mode: "Manual",
    like: false,
  },
  {
    id: "053",
    brand: "Kia",
    capacity: "5",
    fuelType: "Hybrid",
    mileage: "5.9",
    rentPrice: "360",
    year: 2020,
    mode: "Automatic",
    like: false,
  },
  {
    id: "054",
    brand: "Ford",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "6.3",
    rentPrice: "410",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "055",
    brand: "Chevrolet",
    capacity: "4",
    fuelType: "Electric",
    mileage: "4.8",
    rentPrice: "310",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "056",
    brand: "Hyundai",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.6",
    rentPrice: "440",
    year: 2020,
    mode: "Manual",
    like: false,
  },
  {
    id: "057",
    brand: "Mazda",
    capacity: "5",
    fuelType: "Hybrid",
    mileage: "5.5",
    rentPrice: "370",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
  {
    id: "058",
    brand: "Subaru",
    capacity: "4",
    fuelType: "Gasoline",
    mileage: "6.2",
    rentPrice: "400",
    year: 2021,
    mode: "Automatic",
    like: false,
  },
  {
    id: "059",
    brand: "Volkswagen",
    capacity: "4",
    fuelType: "Hybrid",
    mileage: "5.7",
    rentPrice: "360",
    year: 2020,
    mode: "Manual",
    like: false,
  },
  {
    id: "060",
    brand: "Chrysler",
    capacity: "5",
    fuelType: "Gasoline",
    mileage: "6.7",
    rentPrice: "430",
    year: 2022,
    mode: "Automatic",
    like: false,
  },
];

export default carsData;
